export default [
    {
        id: 6,
        adult: false,
        backdrop_path: '/5aXp2s4l6g5PcMMesIj63mx8hmJ.jpg',
        budget: 21000000,
        homepage: '',
        imdb_id: 'tt0107286',
        original_language: 'en',
        original_title: 'Judgment Night',
        overview:
            'While racing to a boxing match, Frank, Mike, John and Rey get more than they bargained for. A wrong turn lands them directly in the path of Fallon, a vicious, wise-cracking drug lord. After accidentally witnessing Fallon murder a disloyal henchman, the four become his unwilling prey in a savage game of cat and mouse as they are mercilessly stalked through the urban jungle in this taut suspense drama.',
        popularity: 10.516,
        poster_path: '/rYFAvSPlQUCebayLcxyK79yvtvV.jpg',
        release_date: '1993-10-15',
        status: 'Released',
        title: 'Judgment Night',
        vote_average: 6.5,
        vote_count: 220,
        runtime: 110,
    },
    {
        id: 12,
        adult: false,
        backdrop_path: '/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg',
        budget: 94000000,
        homepage: 'http://movies.disney.com/finding-nemo',
        imdb_id: 'tt0266543',
        original_language: 'en',
        original_title: 'Finding Nemo',
        overview:
            "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        popularity: 96.414,
        poster_path: '/adMZmqi7LlZB3I8BIE6MpPdzOlG.jpg',
        release_date: '2003-05-30',
        status: 'Released',
        title: 'Finding Nemo',
        vote_average: 7.8,
        vote_count: 15916,
        runtime: 100,
    },
    {
        id: 13,
        adult: false,
        backdrop_path: '/qdIMHd4sEfJSckfVJfKQvisL02a.jpg',
        budget: 55000000,
        homepage: '',
        imdb_id: 'tt0109830',
        original_language: 'en',
        original_title: 'Forrest Gump',
        overview:
            'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
        popularity: 51.533,
        poster_path: '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
        release_date: '1994-07-06',
        status: 'Released',
        title: 'Forrest Gump',
        vote_average: 8.5,
        vote_count: 22026,
        runtime: 142,
    },
    {
        id: 14,
        adult: false,
        backdrop_path: '/DztBnZaqmla2sGUW9s8AyOmskT.jpg',
        budget: 15000000,
        homepage: '',
        imdb_id: 'tt0169547',
        original_language: 'en',
        original_title: 'American Beauty',
        overview:
            "Lester Burnham, a depressed suburban father in a mid-life crisis, decides to turn his hectic life around after developing an infatuation with his daughter's attractive friend.",
        popularity: 28.998,
        poster_path: '/wby9315QzVKdW9BonAefg8jGTTb.jpg',
        release_date: '1999-09-15',
        status: 'Released',
        title: 'American Beauty',
        vote_average: 8,
        vote_count: 9945,
        runtime: 122,
    },
    {
        id: 15,
        adult: false,
        backdrop_path: '/ruF3Lmd4A8MHbnEBE6lxPMbsHGL.jpg',
        budget: 839727,
        homepage: '',
        imdb_id: 'tt0033467',
        original_language: 'en',
        original_title: 'Citizen Kane',
        overview:
            'Newspaper magnate, Charles Foster Kane is taken from his mother as a boy and made the ward of a rich industrialist. As a result, every well-meaning, tyrannical or self-destructive move he makes for the rest of his life appears in some way to be a reaction to that deeply wounding event.',
        popularity: 22.798,
        poster_path: '/gzYbXKwFMBBoE5lTtGsyLBYwvMs.jpg',
        release_date: '1941-04-17',
        status: 'Released',
        title: 'Citizen Kane',
        vote_average: 8,
        vote_count: 4247,
        runtime: 119,
    },
    {
        id: 16,
        adult: false,
        backdrop_path: '/ikR2qy9xJCHX7M8i5rcvuNfdYXs.jpg',
        budget: 12800000,
        homepage: '',
        imdb_id: 'tt0168629',
        original_language: 'en',
        original_title: 'Dancer in the Dark',
        overview:
            "Selma, a Czech immigrant on the verge of blindness, struggles to make ends meet for herself and her son, who has inherited the same genetic disorder and will suffer the same fate without an expensive operation. When life gets too difficult, Selma learns to cope through her love of musicals, escaping life's troubles - even if just for a moment - by dreaming up little numbers to the rhythmic beats of her surroundings.",
        popularity: 15.707,
        poster_path: '/9rsivF4sWfmBzrNr4LPu6TNJhXX.jpg',
        release_date: '2000-06-30',
        status: 'Released',
        title: 'Dancer in the Dark',
        vote_average: 7.9,
        vote_count: 1333,
        runtime: 141,
    },
    {
        id: 18,
        adult: false,
        backdrop_path: '/wgvc3PmjQGtYYDWaeuV867mnFDs.jpg',
        budget: 90000000,
        homepage: '',
        imdb_id: 'tt0119116',
        original_language: 'en',
        original_title: 'The Fifth Element',
        overview:
            'In 2257, a taxi driver is unintentionally given the task of saving a young girl who is part of the key that will ensure the survival of humanity.',
        popularity: 46.208,
        poster_path: '/fPtlCO1yQtnoLHOwKtWz7db6RGU.jpg',
        release_date: '1997-05-02',
        status: 'Released',
        title: 'The Fifth Element',
        vote_average: 7.5,
        vote_count: 8719,
        runtime: 126,
    },
    {
        id: 19,
        adult: false,
        backdrop_path: '/r8pUcom5Mw8igtBpj3AHSAUvH0R.jpg',
        budget: 1300000,
        homepage: '',
        imdb_id: 'tt0017136',
        original_language: 'de',
        original_title: 'Metropolis',
        overview:
            "In a futuristic city sharply divided between the working class and the city planners, the son of the city's mastermind falls in love with a working class prophet who predicts the coming of a savior to mediate their differences.",
        popularity: 18.898,
        poster_path: '/hUK9rewffKGqtXynH5SW3v9hzcu.jpg',
        release_date: '1927-02-06',
        status: 'Released',
        title: 'Metropolis',
        vote_average: 8.2,
        vote_count: 1959,
        runtime: 149,
    },
];
